version: '3.8'

services:
  hr-worker-pg12:
    image: postgres:12-alpine
    container_name: hr-worker-pg12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: db_hr_worker
    ports:
      - "5433:5432"
    volumes:
      - hr-worker-pg12-data:/var/lib/postgresql/data

  hr-user-pg12:
    image: postgres:12-alpine
    container_name: hr-user-pg12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: db_hr_user
    ports:
      - "5434:5432"
    volumes:
      - hr-user-pg12-data:/var/lib/postgresql/data

  hr-config-server:
    image: hr-config-server:v1
    container_name: hr-config-server
    ports:
        - "8888:8888"

  hr-eureka-server:
    image: hr-eureka-server:v1
    container_name: hr-eureka-server
    ports:
      - "8761:8761"

volumes:
  hr-worker-pg12-data: {}
  hr-user-pg12-data: {}

networks:
  default:
    name: hr-net