server:
  port: ${PORT:0}

spring:
  profiles:
    active: prod
  config:
    import: configserver:http://hr-config-server:8888

  application:
    name: hr-worker

  jpa:
    defer-datasource-initialization: true

eureka:
  client:
    service-url:
      defaultZone: http://hr-eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Permite que o actuator atualize as configurações em runtime
management:
  endpoints:
    web:
      exposure:
        include: "*"
