spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/ViniConforti/ms-course-config

server:
  port: 8888
