spring:
  application:
    name: hr-user

  profiles:
    active: test
  config:
    import: configserver:http://localhost:8888

  jpa:
    defer-datasource-initialization: true


server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Permite que o actuator atualize as configurações em runtime
management:
  endpoints:
    web:
      exposure:
        include: "*"
